

export interface Proyecto {
    numero: string,
    nombre: string,
    cliente: string,
    asignado: string,
    cantidadTareasTotales: number,
    cantidadTareasAtrasadas: number,
    porcentajeTareasAtrasadas: number,
    porcentajeTareasATiempo: number,
    porcentajeHPCompletadas: number,
    porcentajeHPEnProgreso: number,
    porcentajeHPEnPrueba: number,
    porcentajeHPNoIniciadas: number,
    porcentajeHPEnPruebaDiseñoFuncional: number,
    porcentajeHPNoIniciadasDiseñoFuncional: number,
    porcentajeHPCompletadasDiseñoFuncional: number,
    porcentajeHPEnProgresoDiseñoFuncional: number,
    porcentajeHPEnPruebaDiseñoTecnico: number,
    porcentajeHPNoIniciadasDiseñoTecnico: number,
    porcentajeHPCompletadasDiseñoTecnico: number,
    porcentajeHPEnProgresoDiseñoTecnico: number,
    porcentajeHPEnPruebaDesarrollo: number,
    porcentajeHPNoIniciadasDesarrollo: number,
    porcentajeHPCompletadasDesarrollo: number,
    porcentajeHPEnProgresoDesarrollo: number,
    porcentajeHPEnPruebaTesting: number,
    porcentajeHPNoIniciadasTesting: number,
    porcentajeHPCompletadasTesting: number,
    porcentajeHPEnProgresoTesting: number
}
